#include "gsinit.h"

void GS_InitVertexDescriptors(void) {
  /* NINTENDO SDK FUNCTIONS
  GXClearVtxDesc();
  GXSetVtxAttrFmt(GX_VTXFMT0,GX_VA_POS,GX_NRM_NBT,GX_RGBA4,0);
  GXSetVtxAttrFmt(GX_VTXFMT0,GX_VA_TEX0,GX_NRM_NBT,GX_RGBA4,1);
  GXSetVtxAttrFmt(GX_VTXFMT1,GX_VA_POS,GX_NRM_NBT,GX_F32,0);
  GXSetVtxAttrFmt(GX_VTXFMT1,GX_VA_CLR0,GX_NRM_NBT,GX_RGBA8,0);
  GXSetVtxAttrFmt(GX_VTXFMT1,GX_VA_TEX0,GX_NRM_NBT,GX_F32,0);
  GXSetVtxAttrFmt(GX_VTXFMT2,GX_VA_POS,GX_NRM_NBT,GX_F32,0);
  GXSetVtxAttrFmt(GX_VTXFMT2,GX_VA_NRM,GX_CLR_RGB,GX_F32,0);
  GXSetVtxAttrFmt(GX_VTXFMT2,GX_VA_CLR0,GX_NRM_NBT,GX_RGBA8,0);
  GXSetVtxAttrFmt(GX_VTXFMT2,GX_VA_TEX0,GX_NRM_NBT,GX_F32,0);
  GXSetVtxAttrFmt(GX_VTXFMT7,GX_VA_POS,GX_NRM_NBT,GX_F32,0);
  GXSetVtxAttrFmt(GX_VTXFMT7,GX_VA_CLR0,GX_NRM_NBT,GX_RGBA8,0);*/
  return;
}
